version: '3.8'

services:
  qdrant-db:
    image: qdrant/qdrant:latest
    container_name: apicopilot-qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage


  rag-service:
    build: ./services/rag_service
    container_name: apicopilot-rag
    ports:
      - "8002:8002"
    environment:
      - QDRANT_HOST=qdrant-db
      - QDRANT_PORT=6333
    depends_on:
      qdrant-db:
        condition: service_started

  orchestrator-service:
    build: ./services/orchestrator_service
    container_name: apicopilot-orchestrator
    ports:
      - "8001:8001"
    environment:
      - RAG_SERVICE_URL=http://rag-service:8002
      - OLLAMA_HOST=http://host.docker.internal:11434
      - LLM_MODEL=codellama:7b-instruct
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - rag-service

  ui-service:
    build: ./services/ui_service
    container_name: apicopilot-ui
    ports:
      - "8000:8000"
    environment:
      - ORCHESTRATOR_URL=http://orchestrator-service:8001
    depends_on:
      - orchestrator-service

volumes:
  qdrant_storage:
